apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-blue
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      release: blue
  template:
    metadata:
      labels:
        app: demo-app
        release: blue
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Blue!"
          ports:
            - containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
