apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: argo
spec:
  type: ClusterIP
  selector:
    app: demo-app
    release: blue
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP