apiVersion: v1
kind: Service
metadata:
  name: demo-app-canary
  namespace: argo
spec:
  type: ClusterIP
  selector:
    app: demo-app
    release: canary
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
