apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rb
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin  # or edit if you want more restriction
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo
