- name: Deploy canary version
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
  tasks:
    - name: Apply canary deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: demo-app-canary
            namespace: argo
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: demo-app
                release: canary
            template:
              metadata:
                labels:
                  app: demo-app
                  release: canary
              spec:
                containers:
                  - name: echo
                    image: hashicorp/http-echo
                    args:
                      - "-text=Hello from Canary v2.0!"
                    ports:
                      - containerPort: 5678
                    readinessProbe:
                      httpGet:
                        path: /
                        port: 5678
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      timeoutSeconds: 1
                      successThreshold: 1
                      failureThreshold: 3

    - name: Apply canary service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: demo-app-canary
            namespace: argo
          spec:
            type: ClusterIP
            selector:
              app: demo-app
              release: canary
            ports:
              - port: 80
                targetPort: 5678
                protocol: TCP
