- name: Apply green version
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
  tasks:
    - name: Apply green deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: demo-app-green
            namespace: argo
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: demo-app
                release: green
            template:
              metadata:
                labels:
                  app: demo-app
                  release: green
              spec:
                containers:
                  - name: echo
                    image: hashicorp/http-echo
                    args:
                      - "-text=Hello from Green!"
                    ports:
                      - containerPort: 5678
                    readinessProbe:
                      httpGet:
                        path: /
                        port: 5678
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      timeoutSeconds: 1
                      successThreshold: 1
                      failureThreshold: 3
