- name: Rollback canary deployment
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
  tasks:
    - name: Ensure main service points back to blue
      kubernetes.core.k8s:
        state: present
        kind: Service
        name: demo-app
        namespace: argo
        merge_type:
          - strategic-merge
        definition:
          spec:
            selector:
              app: demo-app
              release: blue

    - name: Scale blue back to full capacity
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: demo-app-blue
        namespace: argo
        merge_type: merge
        definition:
          spec:
            replicas: 3

    - name: Scale down canary deployment
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: demo-app-canary
        namespace: argo
        merge_type: merge
        definition:
          spec:
            replicas: 0

    - name: Remove canary service
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        name: demo-app-canary
        namespace: argo
